# Generated by Django 4.0.3 on 2022-03-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_mutualfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='income',
            field=models.IntegerField(default='00000'),
        ),
    ]
